### ISSUE TITLE
Provide a more useful message when the plugin can't authenticate with the Qiita server

### ISSUE THREAD

**Issue by josenavas** [qiita-spots/qiita_client#13]
Right now is just saying [`"Can't authenticate with the Qiita server"`](https://github.com/qiita-spots/qiita_client/blob/master/qiita_client/qiita_client.py#L188) which is not useful for debugging. Writing at least the status code returned and `r.reason` should be enough to help debugging.

Noticed this in the test environment when no server was running to authenticate the plugin.

**Comment by antgonza** [comment]
Solved here: https://github.com/qiita-spots/qiita_client/pull/38
